# Generated by Django 2.2 on 2019-04-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Class')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('midT0', models.FloatField()),
                ('midTxp', models.FloatField()),
                ('midTp', models.FloatField()),
                ('midTB', models.FloatField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Group')),
            ],
            options={
                'verbose_name': 'Subgroup',
                'verbose_name_plural': 'Subgroups',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('T0', models.FloatField()),
                ('Txp', models.FloatField()),
                ('Tp', models.FloatField()),
                ('TB', models.FloatField()),
                ('Info', models.TextField(blank=True)),
                ('date_of_ading', models.DateField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Class')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Company')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Group')),
                ('subgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.SubGroup')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
            },
        ),
    ]
