# Generated by Django 2.0.7 on 2019-04-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HandBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='class_id',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='company_id',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='group_id',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='subgroup_id',
            new_name='Subgroup',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='date_of_ading',
            new_name='date_of_adding',
        ),
    ]
