# Generated by Django 2.0.7 on 2019-04-24 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HandBook', '0002_auto_20190423_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handbook_name', models.CharField(default='user_handbook', max_length=30)),
                ('elements', models.CharField(blank=True, default='', max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handbook',
                'verbose_name_plural': 'Handbooks',
            },
        ),
    ]
