# Generated by Django 2.0.7 on 2019-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandBook', '0003_handbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='date_of_adding',
            field=models.CharField(default='2019.4.24, 13:18', max_length=30),
        ),
    ]
