# Generated by Django 2.2 on 2019-05-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandBook', '0004_handbook_date_of_adding'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='confirm_link',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='date_of_adding',
            field=models.CharField(default='2019.5.10, 0:25', max_length=30),
        ),
    ]
