# Generated by Django 2.2 on 2019-05-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandBook', '0005_auto_20190510_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='date_of_adding',
            field=models.CharField(default='2019.5.10, 0:37', max_length=30),
        ),
    ]
