# Generated by Django 2.2 on 2019-05-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandBook', '0006_auto_20190510_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='date_of_adding',
            field=models.CharField(default='2019.5.10, 1:4', max_length=30),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
