# Generated by Django 2.2 on 2019-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandBook', '0007_auto_20190510_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='date_of_adding',
            field=models.CharField(default='2019.5.12, 17:0', max_length=30),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='midT0',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='midTB',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='midTp',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='midTxp',
            field=models.FloatField(blank=True),
        ),
    ]
