# Generated by Django 2.0.7 on 2019-05-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandBook', '0008_auto_20190512_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'verbose_name': 'Подргуппа', 'verbose_name_plural': 'Подгруппы'},
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='date_of_adding',
            field=models.CharField(default='2019.5.24, 0:32', max_length=30),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='midT0',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Средняя наработка на отказ'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='midTB',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Среднее время восстановления (ч)'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='midTp',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Средний ресурс (ч)'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='midTxp',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Средний срок сохраняемости'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
