# Generated by Django 2.2 on 2019-05-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20190408_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmed_elements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
