# Generated by Django 2.0.7 on 2019-05-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('Class', models.CharField(max_length=100, verbose_name='Класс')),
                ('Group', models.CharField(max_length=100, verbose_name='Группа')),
                ('Subgroup', models.CharField(max_length=100, verbose_name='Подгруппа')),
                ('Company', models.CharField(max_length=100, verbose_name='Компания')),
                ('Maintainability', models.CharField(max_length=100, verbose_name='Ремонтопригодность')),
                ('MTBF', models.CharField(max_length=20, verbose_name='MTBF')),
                ('Source', models.CharField(max_length=100, verbose_name='Источник')),
                ('Info', models.TextField(blank=True, verbose_name='Доп. Информация')),
                ('user_id', models.IntegerField(default=0, verbose_name='Пользовательский id')),
            ],
            options={
                'verbose_name': 'Предложенный элемент',
                'verbose_name_plural': 'Предложенные элементы',
            },
        ),
    ]
