# Generated by Django 2.0.7 on 2019-05-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElementOffer', '0002_auto_20190510_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offeredelement',
            options={'verbose_name': 'Предложенный элемент', 'verbose_name_plural': 'Предложенные элементы'},
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='Class',
            field=models.CharField(max_length=100, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='Company',
            field=models.CharField(max_length=100, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='Group',
            field=models.CharField(max_length=100, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='Info',
            field=models.TextField(blank=True, verbose_name='Доп. Информация'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='MTBF',
            field=models.CharField(max_length=20, verbose_name='MTBF'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='Maintainability',
            field=models.CharField(max_length=100, verbose_name='Ремонтопригодность'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='Source',
            field=models.CharField(max_length=100, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='Subgroup',
            field=models.CharField(max_length=100, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='offeredelement',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='Пользовательский id'),
        ),
    ]
