# Generated by Django 2.2 on 2019-05-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HandBook', '0007_auto_20190510_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('T0', models.FloatField()),
                ('Txp', models.FloatField()),
                ('Tp', models.FloatField()),
                ('TB', models.FloatField()),
                ('Info', models.TextField(blank=True)),
                ('date_of_adding', models.DateField()),
                ('confirm_link', models.CharField(default='None', max_length=100)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Class')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Company')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Group')),
                ('Subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.SubGroup')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
            },
        ),
    ]
