# Generated by Django 2.0.7 on 2019-05-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HandBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('T0', models.FloatField(verbose_name='Средняя наработка на отказ')),
                ('Txp', models.FloatField(verbose_name='Средний срок сохраняемости')),
                ('Tp', models.FloatField(verbose_name='Средний ресурс (ч)')),
                ('TB', models.FloatField(verbose_name='Среднее время восстановления (ч)')),
                ('Info', models.TextField(blank=True, verbose_name='Доп. Информация')),
                ('date_of_adding', models.DateField(verbose_name='Дата добавления')),
                ('confirm_link', models.CharField(default='None', max_length=100, verbose_name='Подтверждающая ссылка')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Class', verbose_name='Класс')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Company', verbose_name='Компания')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Group', verbose_name='Группа')),
                ('Subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.SubGroup', verbose_name='Подгруппа')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
