# Generated by Django 2.0.7 on 2019-05-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterField(
            model_name='element',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='element',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='element',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='element',
            name='Info',
            field=models.TextField(blank=True, verbose_name='Доп. Информация'),
        ),
        migrations.AlterField(
            model_name='element',
            name='Subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandBook.SubGroup', verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='element',
            name='T0',
            field=models.FloatField(verbose_name='Средняя наработка на отказ'),
        ),
        migrations.AlterField(
            model_name='element',
            name='TB',
            field=models.FloatField(verbose_name='Среднее время восстановления (ч)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='Tp',
            field=models.FloatField(verbose_name='Средний ресурс (ч)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='Txp',
            field=models.FloatField(verbose_name='Средний срок сохраняемости'),
        ),
        migrations.AlterField(
            model_name='element',
            name='confirm_link',
            field=models.CharField(default='None', max_length=100, verbose_name='Подтверждающая ссылка'),
        ),
        migrations.AlterField(
            model_name='element',
            name='date_of_adding',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
